repository-url: https://raw.githubusercontent.com/mitre-attack/attack-stix-data/master
version: 16.1
mitre-object-types:
  tactics: true
  techniques: false
  mitigations: true
  groups: false
  software: false
